seed: 42

n_timesteps: !!float 2e7
policy: 'MlpPolicy'
learning_rate: !!float 3.0e-4
buffer_size: 1000000
learning_starts: 10000
batch_size: 256 
tau: 0.001
gamma: 0.99
train_freq: 1
gradient_steps: 16
ent_coef: "auto_0.02"
target_entropy: -7
use_sde: True
policy_kwargs:
  net_arch: [256, 256]
  log_std_init: -2.0
device: "cuda:0"
